"use client";

import { ArrowLeft, ArrowRight, Check, Lightbulb, RotateCcw } from "lucide-react";
import { useEffect, useState } from "react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { TransitionLink } from "@/components/shared/navigation-transition";
import { useCelebration } from "@/components/shared/celebration-provider";
import { createAttempt, createQuizSession, scoreQuiz } from "@/lib/quiz-utils";
import { cn } from "@/lib/utils";
import type { QuizSession } from "@/lib/types";
import { useRoadmap } from "@/state/roadmap-store";
import { QuestionCard } from "./question-card";

export function QuizRunner({ quizId }: { quizId: string }) {
  const { state, dispatch } = useRoadmap(); const { celebrate } = useCelebration(); const quiz = state.quizzes.find((item) => item.id === quizId); const [finishOpen, setFinishOpen] = useState(false);
  useEffect(() => { if (quiz && !quiz.session) dispatch({ type: "SET_QUIZ_SESSION", payload: { quizId, session: createQuizSession() } }); }, [quiz, quizId, dispatch]);
  if (!quiz) return <div className="mx-auto max-w-xl py-16 text-center"><h2 className="text-lg font-semibold">Quiz not found</h2><p className="mt-2 text-sm text-muted-foreground">It may have been removed or belonged to an earlier preview session.</p><TransitionLink href={`/roadmaps/${state.roadmap.slug}/quiz`} className="mt-4 inline-flex text-sm font-medium text-primary hover:underline">Back to quizzes</TransitionLink></div>;
  const session = quiz.session; if (!session) return null;
  const setSession = (next: QuizSession) => dispatch({ type: "SET_QUIZ_SESSION", payload: { quizId, session: next } });
  const question = quiz.definition.questions[session.currentIndex]; const selected = question ? session.selectedAnswers[question.id] ?? null : null; const checked = question ? session.checkedQuestionIds.includes(question.id) || session.view !== "taking" : false; const answered = Object.keys(session.selectedAnswers).length; const unanswered = quiz.definition.questions.length - answered;
  const finish = () => { const resolved = { ...session, checkedQuestionIds: quiz.definition.questions.map((item) => item.id), view: "results" as const }; const attempt = createAttempt(quiz, resolved); dispatch({ type: "FINISH_QUIZ", payload: { quizId, attempt, session: resolved } }); setFinishOpen(false); if (attempt.percent >= 80) celebrate({ kind: "quiz-win", quizTitle: quiz.definition.title, score: attempt.correct, total: attempt.total }); };
  const restart = () => setSession(createQuizSession());
  if (!quiz.definition.questions.length) return <div className="rounded-lg border border-dashed px-5 py-12 text-center"><h2 className="text-sm font-semibold">This quiz has no questions</h2><p className="mt-1 text-sm text-muted-foreground">Return to the library and edit it before starting.</p><TransitionLink className="mt-4 inline-flex text-sm font-medium text-primary" href={`/roadmaps/${state.roadmap.slug}/quiz`}>Back to quizzes</TransitionLink></div>;
  if (session.view === "results") { const score = scoreQuiz(quiz, session); return <div className="mx-auto max-w-3xl"><TransitionLink href={`/roadmaps/${state.roadmap.slug}/quiz`} className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft /> Quizzes</TransitionLink><div className="mt-4 rounded-lg border bg-surface-raised p-6 text-center"><h2 className="text-xl font-semibold">{score.percent === 100 ? "A perfect run." : score.percent >= 70 ? "Strong work." : "Keep building on it."}</h2><p className="mt-1 text-sm text-muted-foreground">{quiz.definition.title}</p><div className="mx-auto mt-5 grid max-w-md grid-cols-4 divide-x rounded-md border"><div className="p-3"><strong className="block text-xl">{score.percent}%</strong><span className="text-xs text-muted-foreground">Score</span></div><div className="p-3"><strong className="block text-xl">{score.correct}</strong><span className="text-xs text-muted-foreground">Correct</span></div><div className="p-3"><strong className="block text-xl">{score.incorrect}</strong><span className="text-xs text-muted-foreground">Incorrect</span></div><div className="p-3"><strong className="block text-xl">{score.unanswered}</strong><span className="text-xs text-muted-foreground">Skipped</span></div></div><div className="mt-5 flex justify-center gap-2"><Button variant="outline" onClick={() => setSession({ ...session, currentIndex: 0, view: "review" })}>Review answers</Button><Button onClick={restart}><RotateCcw /> Retake</Button></div></div></div>; }
  return <div><div className="mb-4 flex items-center justify-between gap-4"><div><TransitionLink href={`/roadmaps/${state.roadmap.slug}/quiz`} className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft /> Quizzes</TransitionLink><h2 className="mt-2 text-lg font-semibold">{quiz.definition.title}</h2></div><span className="font-mono text-xs text-muted-foreground">{answered}/{quiz.definition.questions.length} answered</span></div><Progress value={(answered / quiz.definition.questions.length) * 100} className="mb-4 h-1.5" />
    <div className="grid items-start gap-3 lg:grid-cols-[16rem_minmax(0,1fr)]"><aside className="rounded-lg border bg-surface-raised p-3 lg:sticky lg:top-24"><div className="flex gap-1 overflow-x-auto lg:grid">{quiz.definition.questions.map((item, index) => { const isChecked = session.checkedQuestionIds.includes(item.id) || session.view === "review"; const answerId = session.selectedAnswers[item.id]; const correct = isChecked && item.answers.find((answer) => answer.id === answerId)?.correct; return <button key={item.id} className={cn("flex min-w-11 items-center gap-2 rounded-md px-2 py-2 text-left text-xs hover:bg-accent lg:min-w-0", index === session.currentIndex && "bg-secondary text-secondary-foreground", isChecked && correct && "text-primary", isChecked && answerId && !correct && "text-destructive")} onClick={() => setSession({ ...session, currentIndex: index })}><span className="grid size-6 shrink-0 place-items-center rounded border font-mono">{isChecked ? correct ? <Check className="size-3.5" /> : "×" : index + 1}</span><span className="hidden truncate lg:block">{item.question}</span></button>; })}</div></aside>
      <div><QuestionCard question={{ ...question, selectedAnswerID: selected }} index={session.currentIndex} selected={selected} checked={checked} hintVisible={session.hintQuestionIds.includes(question.id)} onHintChange={(visible) => setSession({ ...session, hintQuestionIds: visible ? [...session.hintQuestionIds, question.id] : session.hintQuestionIds.filter((id) => id !== question.id) })} onSelect={(answerId) => setSession({ ...session, selectedAnswers: { ...session.selectedAnswers, [question.id]: answerId } })} /><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={session.currentIndex === 0} onClick={() => setSession({ ...session, currentIndex: session.currentIndex - 1 })}><ArrowLeft /> Previous</Button>{session.view === "taking" && selected && !checked && <Button variant="ghost" onClick={() => { const selectedAnswers = { ...session.selectedAnswers }; delete selectedAnswers[question.id]; setSession({ ...session, selectedAnswers }); }}><RotateCcw /> Clear answer</Button>}{session.view === "taking" && <Button variant="outline" disabled={!selected || checked} onClick={() => setSession({ ...session, checkedQuestionIds: [...session.checkedQuestionIds, question.id] })}><Check /> Check answer</Button>}</div>{session.currentIndex < quiz.definition.questions.length - 1 ? <Button onClick={() => setSession({ ...session, currentIndex: session.currentIndex + 1 })}>Next <ArrowRight /></Button> : session.view === "review" ? <Button onClick={() => setSession({ ...session, view: "results" })}>Back to results</Button> : <Button onClick={() => unanswered ? setFinishOpen(true) : finish()}>Finish quiz</Button>}</div></div>
    </div><AlertDialog open={finishOpen} onOpenChange={setFinishOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Finish with {unanswered} unanswered?</AlertDialogTitle><AlertDialogDescription>Unanswered questions will be recorded as skipped. You can go back and answer them first.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep working</AlertDialogCancel><AlertDialogAction onClick={finish}>Finish quiz</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}
