"use client";

import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { QuizAnswer, QuizDefinition, QuizDefinitionQuestion, SavedQuiz } from "@/lib/types";

const answer = (): QuizAnswer => ({ id: crypto.randomUUID(), text: "", correct: false, explanation: "" });
const question = (): QuizDefinitionQuestion => ({ id: crypto.randomUUID(), question: "", hint: "", answers: [answer(), answer(), answer(), answer()] });
const move = <T,>(items: T[], index: number, direction: -1 | 1) => { const next = [...items]; const target = index + direction; if (target < 0 || target >= next.length) return next; [next[index], next[target]] = [next[target], next[index]]; return next; };

export function QuizEditorDialog({ open, onOpenChange, quiz, onSave }: { open: boolean; onOpenChange: (open: boolean) => void; quiz: SavedQuiz | null; onSave: (definition: QuizDefinition) => void }) {
  const [definition, setDefinition] = useState<QuizDefinition>({ version: 1, title: "Untitled quiz", questions: [] });
  useEffect(() => { if (open) setDefinition(quiz?.definition ?? { version: 1, title: "Untitled quiz", questions: [] }); }, [open, quiz]);
  const updateQuestion = (index: number, patch: Partial<QuizDefinitionQuestion>) => setDefinition((value) => ({ ...value, questions: value.questions.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) }));
  const valid = definition.title.trim().length > 0 && definition.questions.length > 0 && definition.questions.every((item) => item.question.trim() && item.hint.trim() && item.answers.length === 4 && item.answers.every((option) => option.text.trim() && option.explanation.trim()) && item.answers.filter((option) => option.correct).length === 1);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="grid max-h-[92svh] max-w-3xl grid-rows-[auto_minmax(0,1fr)_auto] overflow-hidden p-0"><DialogHeader className="px-6 pt-6 pr-12"><DialogTitle>{quiz ? "Edit quiz" : "Create quiz"}</DialogTitle><DialogDescription>Questions require a hint, exactly four answers, one correct answer, and an explanation for each option.</DialogDescription></DialogHeader>
    <div className="min-h-0 space-y-4 overflow-y-auto px-6 pb-2"><div className="space-y-1.5"><Label htmlFor="quiz-editor-title">Title</Label><Input id="quiz-editor-title" value={definition.title} onChange={(event) => setDefinition({ ...definition, title: event.target.value })} /></div>
      {definition.questions.map((item, index) => <section key={item.id} className="rounded-lg border bg-surface-raised p-4"><div className="mb-3 flex items-center justify-between gap-3"><h3 className="text-sm font-semibold">Question {index + 1}</h3><div className="flex"><Button variant="ghost" size="icon-sm" aria-label="Move question up" disabled={index === 0} onClick={() => setDefinition({ ...definition, questions: move(definition.questions, index, -1) })}><ArrowUp /></Button><Button variant="ghost" size="icon-sm" aria-label="Move question down" disabled={index === definition.questions.length - 1} onClick={() => setDefinition({ ...definition, questions: move(definition.questions, index, 1) })}><ArrowDown /></Button><Button variant="ghost" size="icon-sm" aria-label="Delete question" onClick={() => setDefinition({ ...definition, questions: definition.questions.filter((_, itemIndex) => itemIndex !== index) })}><Trash2 /></Button></div></div>
        <div className="grid gap-3"><Input aria-label={`Question ${index + 1} text`} placeholder="Question" value={item.question} onChange={(event) => updateQuestion(index, { question: event.target.value })} /><Input aria-label={`Question ${index + 1} hint`} placeholder="Hint" value={item.hint} onChange={(event) => updateQuestion(index, { hint: event.target.value })} />
          <div className="grid gap-2">{item.answers.map((option, answerIndex) => <div key={option.id} className="grid grid-cols-[auto_minmax(0,1fr)_minmax(0,1fr)_auto] items-center gap-2 max-sm:grid-cols-[auto_minmax(0,1fr)_auto]"><input type="radio" name={`correct-${item.id}`} checked={option.correct} aria-label={`Mark answer ${answerIndex + 1} correct`} onChange={() => updateQuestion(index, { answers: item.answers.map((entry) => ({ ...entry, correct: entry.id === option.id })) })} /><Input aria-label={`Answer ${answerIndex + 1}`} placeholder={`Answer ${answerIndex + 1}`} value={option.text} onChange={(event) => updateQuestion(index, { answers: item.answers.map((entry) => entry.id === option.id ? { ...entry, text: event.target.value } : entry) })} /><Input className="max-sm:col-start-2" aria-label={`Explanation ${answerIndex + 1}`} placeholder="Explanation" value={option.explanation} onChange={(event) => updateQuestion(index, { answers: item.answers.map((entry) => entry.id === option.id ? { ...entry, explanation: event.target.value } : entry) })} /><div className="flex"><Button variant="ghost" size="icon-sm" disabled={answerIndex === 0} aria-label={`Move answer ${answerIndex + 1} up`} onClick={() => updateQuestion(index, { answers: move(item.answers, answerIndex, -1) })}><ArrowUp /></Button><Button variant="ghost" size="icon-sm" disabled={answerIndex === item.answers.length - 1} aria-label={`Move answer ${answerIndex + 1} down`} onClick={() => updateQuestion(index, { answers: move(item.answers, answerIndex, 1) })}><ArrowDown /></Button><Button variant="ghost" size="icon-sm" aria-label={`Delete answer ${answerIndex + 1}`} onClick={() => updateQuestion(index, { answers: item.answers.filter((entry) => entry.id !== option.id) })}><Trash2 /></Button></div></div>)}</div>
          {item.answers.length < 4 && <Button variant="outline" size="sm" onClick={() => updateQuestion(index, { answers: [...item.answers, answer()] })}><Plus /> Add answer</Button>}
        </div></section>)}
      <Button variant="outline" onClick={() => setDefinition({ ...definition, questions: [...definition.questions, question()] })}><Plus /> Add question</Button>
    </div><DialogFooter className="border-t px-6 py-4"><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={!valid} onClick={() => { onSave({ ...definition, title: definition.title.trim() }); onOpenChange(false); toast.success(quiz ? "Quiz updated" : "Quiz created"); }}>Save quiz</Button></DialogFooter></DialogContent>
  </Dialog>;
}
